name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        dotnet-version:
          - '6.0.x'
        project:
          - TR.CustomDataSharingManager.Tests
          - TR.SMemCtrler.Tests
          - TR.SMemIF.Tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build ${{ matrix.project }}
        run: dotnet build ${{ matrix.project }} -c Release --no-restore
      - name: Test ${{ matrix.project }}
        run: dotnet test ${{ matrix.project }} -c Release --no-build -v normal
