name: Generate docs and upload to Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: sudo apt update

      - name: Setup Doxygen / Graphviz
        run: sudo apt install doxygen graphviz

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build with Doxygen
        run: doxygen

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1